project_id = "xsoienfnqjtxgfgsmynu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.process-document]
verify_jwt = false