// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsoienfnqjtxgfgsmynu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzb2llbmZucWp0eGdmZ3NteW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjUxMjAsImV4cCI6MjA3NDMwMTEyMH0.TD1-1EZSTKMNRdFyCWXNzk9r3fTcJkyYhL8673FZAkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});